- hosts: all
  gather_facts: no
  tasks:
    - name: Deploy OVF Template
      vmware_deploy_ovf:
        ovf: '/mnt/ansible_task_files/ova/{{ova_file}}'
        datastore: '{{datastore}}'
        name: '{{vmname}}'
        power_on: yes
        wait_for_ip_address: true
        validate_certs: false
        
      delegate_to: localhost
