- hosts: all
  gather_facts: no
  tasks:
    - name: Deploy OVF Template
      vmware_deploy_ovf:
        #hostname: '10.0.10.200'
        #username: 'ansible_worker'
        #password: '{{ ansible_worker_password }}'
        ovf: '{{ova_path}}'
        datastore: '{{datastore}}'
        name: '{{item}}'
        power_on: yes
        wait_for_ip_address: true
        validate_certs: false
      delegate_to: localhost
      with_items: "{{vmnames}}"
      async: 600
      poll: 0
      register: ova_worker

    - name: 'OVA Worker - check on async task'
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 30
      retries: 1000
      with_items: "{{ova_worker.results}}"
      delegate_to: localhost