- hosts: all
  gather_facts: no
  tasks:
  - name: Deploy Windows 2019 vm from OVA
    raw: /vmfs/volumes/LOCAL_SSD/vmware-ovftool/ovftool -dm=thin -ds=LOCAL_SSD  -n={{item}} "/vmfs/volumes/QNAP_ISCSI/OVA/{{ovfname}}" "vi://{{ovf_username}}:{{ovf_password}}@127.0.0.1"
    with_items: "{{vmnames}}"
