---#gather facts and display reporrt
#to display on the screen use: ansible windows -i windows -m gather_facts
#to display single variable use: ansible windows -i windows -m debug -a "var=<variable name>"
- hosts: all
  tasks: 
  - debug:
    msg: System {{ inventory_hostname }} has uuid {{ ansible_product_serial }}
