- hosts: "{{pinghosts | default('all')}}"
  gather_facts: yes
  vars:
    win_host_names: []
    
  tasks:
  - name: PING host
    win_ping:
    register: res

  - name: prepare list  
    set_fact:  
     win_host_names: "{{ win_host_names }} + [ '{{ res.ping }}' ]"  

  - name: set stats 
    set_stats:  
        data:  
          current_hostname_list: "{{ win_host_names }}"  
        per_host: no  
