- hosts: "{{pinghosts | default('all')}}"
  gather_facts: no

  tasks:
  - name: PING host
    win_ping:
    register: result
  
  - debug var=result.stdout_lines
    
  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        integration_results_url: "{{failed}}"
