- hosts: all
  gather_facts: no
  vars:
    win_host_names: []
    
  tasks:
  - name: Define pinghosts if not defined
    set_fact:
      pinghosts: []
    when: pinghosts is not defined
  
  - name: PING host
    win_ping:
    register: res
    when: "{{ inventory_hostname }} not in [ '{{ pinghosts }}' ]"

  - name: prepare list failed
    set_fact:  
      win_host_names: "{{ win_host_names }} + [ 'fail' ]"
    when: res is failed

  - name: prepare list skipped
    set_fact:  
      win_host_names: "{{ win_host_names }} + [ 'skip' ]"
    when: res is skipped
    
  - name: prepare list succeeded
    set_fact:  
      win_host_names: "{{ win_host_names }} + [ '{{inventory_hostname}}' ]"
    when: res is succeeded

  - name: set stats 
    set_stats:  
        data:  
          pinghosts: "{{ win_host_names }}"  
        per_host: no
