- hosts: "{{pinghosts | default('all')}}"
  gather_facts: no
  vars:
    win_host_names: []
    
  tasks:
  - name: PING host
    win_ping:
    register: res


  - name: prepare list failed
    set_fact:  
      win_host_names: "{{ win_host_names }} + [ 'fail' ]"
    when: res is failed

  - name: prepare list skipped
    set_fact:  
      win_host_names: "{{ win_host_names }} + [ 'skip' ]"
    
  - name: prepare list succeeded
    set_fact:  
      win_host_names: "{{ win_host_names }} + [ '{{host}}' ]"
    when: res is succeeded

  - name: set stats 
    set_stats:  
        data:  
          current_hostname_list: "{{ win_host_names }}"  
        per_host: no  
