- hosts: '{{ pinghosts | default("all") }}'
  gather_facts: no
  vars:
    hosts_all: []
    hosts_ok: []
    hosts_failed: []
    
  tasks:
  - name: Build a list of all processed hosts
    set_fact:  
      hosts_all: "{{ hosts_all }} + [ '{{inventory_hostname}}' ]"
#    debug:
#      msg: Processing {{ inventory_hostname }}

  - name: PING host
    win_ping:
    register: res
#    ignore_errors: true
    
  - name: Build a list of hosts that are OK
    set_fact:  
      hosts_ok: "{{ hosts_ok }} + [ '{{inventory_hostname}}' ]"
    when: res is succeeded

  - name: Build a list of hosts that had FAILED
    set_fact:
      hosts_failed: "{{ hosts_all | difference(hosts_ok) }}"
      
  - debug: var=hosts_failed
      
  - name: Return hosts that had failed
    set_stats:  
        data:  
          pinghosts: hosts_failed
        per_host: no
