- hosts: "{{pinghosts | default('all')}}"
  gather_facts: no
  vars:  
    win_host_names: []  
  tasks:
  - name: PING host
    win_ping:
    register: result
    
  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        integration_results_url:  "{{ result }}"
